"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardAction,
  CardDescription,
  CardHeader,
  CardTitle,
  CardContent,
} from "@/components/ui/card"
import { MetricCard } from "@/components/dashboard/metric-card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"
import { 
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from "@/components/ui/dialog"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Progress } from "@/components/ui/progress"
import { 
  IconGripVertical,
  IconDotsVertical,
  IconTarget,
  IconExternalLink,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconCopy,
} from "@tabler/icons-react"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { useEffect, useState } from "react"
import type { ScrapeSnapshot } from "@/lib/analysis/technical/types"
import { toast } from "sonner"

// AI Task Generator removed

// Define types
type TaskItem = {
  id: number
  header: string
  type: "GEO" | "SEO" | "Content"
  status: string
  target: string
  limit: string
  progress: number
  priority: string
  dueDate: string
  description: string
  actionItems: string[]
  detailedSteps: DetailedStep[]
  resources: Resource[]
  estimatedTime: string
  difficulty: string
  whyItMatters: string
  impact: string
  // New optional fields when tasks come from generator
  templateKey?: string
  tags?: ("GEO" | "SEO" | "Content")[]
  evidencePaths?: string[]
  verificationCheckDescription?: string
}

type DetailedStep = {
  id: number
  title: string
  description: string
  completed: boolean
  estimatedTime: string
}

type Resource = {
  title: string
  url: string
  type: "documentation" | "tool" | "guide"
}

// AI Task transformation removed

// Removed static tasks - tasks only appear when generated by AI

function DragHandle({ id }: { id: number }) {
  return (
    <Button
      variant="ghost"
      size="icon"
      className="text-white/40 hover:text-white/80 size-7 hover:bg-transparent"
    >
      <IconGripVertical className="size-3" />
      <span className="sr-only">Drag to reorder</span>
    </Button>
  )
}

function PriorityTag({ level }: { level: 'high' | 'medium' | 'low' }) {
  const color = level === 'high' ? 'bg-red-500' : level === 'medium' ? 'bg-amber-500' : 'bg-green-500'
  const label = level === 'high' ? 'High importance' : level === 'medium' ? 'Medium priority' : 'Low priority'
  const bar = `w-1 h-3 rounded-[3px] ring-1 ring-white/10 ${color}`
  return (
    <div className="inline-flex items-center gap-1" aria-label={label} title={label}>
      <span aria-hidden className={bar}></span>
      <span aria-hidden className={bar}></span>
      <span aria-hidden className={bar}></span>
    </div>
  )
}

function TaskDetailModal({ task, displayIndex, onComplete, onVerify, latestSnapshot, verifications }: { task: TaskItem; displayIndex: number; onComplete: (taskId: number) => void; onVerify?: (taskId: number) => void; latestSnapshot?: ScrapeSnapshot | null; verifications?: { time: string; passed: boolean }[] }) {
  const [stepStates, setStepStates] = useState<Record<number, boolean>>({})
  const [expandedStepId, setExpandedStepId] = useState<number | null>(null)

  const toggleStep = (stepId: number) => {
    setStepStates(prev => ({
      ...prev,
      [stepId]: !prev[stepId]
    }))
  }

  const completedSteps = Object.values(stepStates).filter(Boolean).length
  const totalSteps = task.detailedSteps.length
  const progressPercentage = totalSteps > 0 ? (completedSteps / totalSteps) * 100 : 0
  const allStepsDone = totalSteps > 0 && completedSteps === totalSteps

  const copySteps = async () => {
    const text = task.detailedSteps.map((s, i) => `${i + 1}. ${s.title}\n${s.description}`).join("\n\n")
    try { await navigator.clipboard.writeText(text); toast.success("Steps copied") } catch { toast.error("Copy failed") }
  }

  const resolveEvidenceUrl = (pathStr: string): string | undefined => {
    if (!latestSnapshot) return undefined
    try {
      const value = pathStr.split('.').reduce<any>((acc, key) => (acc as any)?.[key], latestSnapshot as any)
      if (typeof value === 'string' && /^https?:\/\//i.test(value)) return value
    } catch { /* ignore */ }
    return undefined
  }

  return (
    <DialogContent className="max-w-6xl max-h-[86vh] p-6 md:p-8 bg-transparent backdrop-blur-sm border border-white/10 rounded-lg flex flex-col">
      <DialogHeader className="pb-3">
        <div className="flex items-start">
          <div>
            <DialogTitle className="text-lg leading-snug font-semibold text-white">
              {task.header}
            </DialogTitle>
            <DialogDescription className="mt-1 text-[13px] md:text-sm text-white/70">
              {task.description}
            </DialogDescription>
          </div>
        </div>
      </DialogHeader>

      <div className="flex-1 overflow-y-auto pr-0 mt-2">
        <Tabs defaultValue="overview" className="px-1">
          <div className="flex items-center justify-between mb-4">
            <TabsList className="bg-transparent border border-white/10 rounded-lg p-1.5 gap-1">
              <TabsTrigger value="overview">Overview</TabsTrigger>
              <TabsTrigger value="steps">Steps</TabsTrigger>
              <TabsTrigger value="resources">Resources</TabsTrigger>
            </TabsList>
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="h-7 rounded text-xs whitespace-nowrap">Priority: {task.priority}</Badge>
            </div>
          </div>

          <TabsContent value="overview">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 md:gap-4">
              <Card className="min-h-[120px] py-4 *:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Progress</CardDescription>
                  <CardTitle className="text-2xl font-bold text-foreground">{progressPercentage.toFixed(0)}%</CardTitle>
                </CardHeader>
              </Card>
              <Card className="min-h-[120px] py-4 *:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Difficulty</CardDescription>
                  <CardTitle className="text-lg font-semibold text-foreground">{task.difficulty}</CardTitle>
                </CardHeader>
              </Card>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 md:gap-4 mt-4">
              <Card className="py-4">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Why it matters</CardDescription>
                  <CardContent className="px-0 pt-2">
                    <p className="text-sm text-muted-foreground leading-relaxed">{task.whyItMatters}</p>
                  </CardContent>
                </CardHeader>
              </Card>
              <Card className="py-4">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Impact</CardDescription>
                  <CardContent className="px-0 pt-2">
                    <p className="text-sm text-muted-foreground leading-relaxed">{task.impact}</p>
                  </CardContent>
                </CardHeader>
              </Card>
              {verifications && (
                <Card className="py-4">
                  <CardHeader className="pb-2">
                    <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Recent verifications</CardDescription>
                    <CardContent className="px-0 pt-2">
                      {verifications.length === 0 ? (
                        <p className="text-sm text-muted-foreground">No verifications yet.</p>
                      ) : (
                        <ul className="text-sm text-muted-foreground leading-relaxed space-y-1">
                          {verifications.slice(-5).reverse().map((v, i) => (
                            <li key={i} className="flex items-center justify-between">
                              <span>{new Date(v.time).toLocaleString()}</span>
                              <Badge variant="outline" className={v.passed ? 'text-emerald-400' : 'text-amber-400'}>{v.passed ? 'Passed' : 'Not yet'}</Badge>
                            </li>
                          ))}
                        </ul>
                      )}
                    </CardContent>
                  </CardHeader>
                </Card>
              )}

              {task.verificationCheckDescription && (
                <Card className="py-4">
                  <CardHeader className="pb-2">
                    <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Verification</CardDescription>
                    <CardContent className="px-0 pt-2">
                      <p className="text-sm text-muted-foreground leading-relaxed">{task.verificationCheckDescription}</p>
                    </CardContent>
                  </CardHeader>
                </Card>
              )}
            </div>
          </TabsContent>

          <TabsContent value="steps">
            {task.detailedSteps.length > 0 && (
            <Card className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs mb-4">
                <CardHeader className="pb-4">
                  <CardTitle className="text-lg font-semibold">Step Progress</CardTitle>
                  <CardDescription className="text-muted-foreground/80">
                    {completedSteps} of {totalSteps} steps completed
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <Progress value={progressPercentage} className="h-3" />
                </CardContent>
              </Card>
            )}
            <Card className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between gap-2">
                  <div>
                    <CardTitle className="text-lg font-semibold">Checklist</CardTitle>
                    <CardDescription className="text-muted-foreground/80">Follow these steps</CardDescription>
                  </div>
                  {task.detailedSteps.length > 0 && (
                    <Button variant="outline" size="sm" onClick={copySteps}>
                      <IconCopy className="size-4 mr-1" /> Copy steps
                    </Button>
                  )}
                </div>
              </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {task.detailedSteps.map((step, index) => (
                  <div
                    key={step.id}
                    className={`group rounded-lg border border-white/10 p-4 bg-transparent hover:bg-white/[0.05] transition-all duration-200 cursor-pointer ${expandedStepId === step.id ? 'ring-1 ring-white/20' : ''} ${stepStates[step.id] ? 'border-emerald-500/30' : ''}`}
                    aria-expanded={expandedStepId === step.id}
                    onClick={() => setExpandedStepId(prev => (prev === step.id ? null : step.id))}
                  >
                    <div className="flex gap-3">
                      <div className={`mt-0.5 flex h-6 w-6 items-center justify-center rounded text-[11px] font-medium ${stepStates[step.id] ? 'bg-emerald-500/20 text-emerald-300' : 'bg-white/10 text-white/70'}`}>{index + 1}</div>
                      <div className="flex-shrink-0 mt-0.5" onClick={(e) => e.stopPropagation()}>
                        <Checkbox
                          checked={stepStates[step.id] || false}
                          onCheckedChange={() => toggleStep(step.id)}
                        />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <h4 className="font-semibold text-white">{step.title}</h4>
                          <div className="ml-auto text-white/60">
                            {expandedStepId === step.id ? (
                              <IconChevronDown className="size-4" />
                            ) : (
                              <IconChevronRight className="size-4" />
                            )}
                          </div>
                        </div>
                        <p className="text-sm text-white/80 leading-relaxed">{step.description}</p>

                        {expandedStepId === step.id && (
                          <div className="mt-3 pt-3 border-t border-white/10 space-y-3">
                            <h5 className="text-sm font-semibold">Detailed instructions</h5>
                            <ol className="list-decimal ml-5 space-y-2 text-sm text-muted-foreground">
                              <li>Prepare: identify the exact files and locations impacted by “{step.title}”. Create a backup or a new branch before changes.</li>
                              <li>Implement: follow the step description precisely. If adding code or JSON-LD, validate with appropriate linters/validators.</li>
                              <li>Verify: test locally and in a staging environment. Use browser devtools and network/SEO tools to confirm results.</li>
                              <li>Document: capture a short note of what changed and why so teammates can follow the context later.</li>
                            </ol>
                            <p className="text-xs text-white/60">Tip: Click the checkbox on the left to mark this step as completed.</p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="resources">
            <Card className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
              <CardHeader className="pb-4">
                <CardTitle className="text-lg font-semibold">Helpful Resources</CardTitle>
                <CardDescription className="text-muted-foreground/80">Tools and guides</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {task.resources.map((resource, index) => (
                    <a key={index} href={resource.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 p-3 border border-white/10 rounded-lg bg-transparent hover:bg-white/[0.05] transition-colors">
                      <div className="w-8 h-8 bg-primary/10 rounded flex items-center justify-center">
                        <IconExternalLink className="size-4 text-primary" />
                      </div>
                      <div className="flex-1">
                        <p className="font-semibold text-sm text-white">{resource.title}</p>
                        <p className="text-xs text-white/70 capitalize">{resource.type}</p>
                      </div>
                    </a>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          
        </Tabs>

        <div className="grid grid-cols-2 gap-5 pt-4">
          <DialogClose asChild>
            <Button
              disabled={!allStepsDone}
              onClick={() => onComplete(task.id)}
              className={`w-full h-11 rounded-lg gap-2 ${allStepsDone ? 'bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary/70' : 'bg-white/5 text-white/40 cursor-not-allowed'}`}
            >
              <IconCheck className="size-4" />
              Mark as Complete
            </Button>
          </DialogClose>
          <Button
            variant="outline"
            className="w-full h-11 rounded-lg"
            onClick={() => {
              document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
              const detail = { initialMessage: `Help me do task number ${displayIndex}` }
              window.dispatchEvent(new CustomEvent('mudra:open-chat', { detail } as any))
            }}
          >
            Ask AI
          </Button>
        </div>
      </div>
    </DialogContent>
  )
}

export function TasksView() {
  const [tasks, setTasks] = useState<TaskItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Latest snapshot to enable Verify requests (can be injected from elsewhere)
  const [latestSnapshot, setLatestSnapshot] = useState<ScrapeSnapshot | null>(null)

  // Fetch tasks from database
  const fetchTasks = async () => {
    try {
      setLoading(true);
      setError(null);
      const siteId = typeof window !== 'undefined' ? (localStorage.getItem('mudra:siteId') || '') : '';
      const response = await fetch(`/api/tasks?siteId=${encodeURIComponent(siteId)}`);
      const result = await response.json();
      
      if (!result.success) {
        throw new Error(result.error?.message || 'Failed to fetch tasks');
      }

      // Convert database tasks to TaskItem format
      const dbTasks = result.data.tasks.map((task: any, index: number) => ({
        id: task.id,
        header: task.title,
        type: (task.tags?.[0] || "SEO") as "GEO" | "SEO" | "Content",
        status: task.status === "open" ? "In Process" : "Done",
        target: "0",
        limit: "100",
        progress: 0,
        priority: task.impact === "High" ? "high" : task.impact === "Medium" ? "medium" : "low",
        dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 1 week from now
        description: task.whyItMatters || "Generated task to improve your technical structure score.",
        whyItMatters: task.whyItMatters || "This addresses a verified gap in your technical structure.",
        impact: task.impact || "Medium",
        actionItems: Array.isArray(task.steps) ? task.steps.slice(0, 3) : [],
        detailedSteps: Array.isArray(task.steps) ? task.steps.map((step: string, i: number) => ({
          id: i + 1,
          title: step.length > 50 ? step.substring(0, 50) + "..." : step,
          description: step,
          completed: false,
          estimatedTime: "30 minutes"
        })) : [],
        resources: [],
        estimatedTime: "1-2 hours",
        difficulty: "medium",
        templateKey: task.templateKey,
        tags: task.tags,
        evidencePaths: Array.isArray(task.evidence) ? task.evidence.map((e: any) => e.path) : [],
        verificationCheckDescription: task.verificationCheck?.description
      }));

      setTasks(dbTasks);
      setLatestSnapshot(result.data.latestSnapshot);
    } catch (err) {
      setError((err as Error).message);
      console.error('Failed to fetch tasks:', err);
    } finally {
      setLoading(false);
    }
  };

  // Initial fetch
  useEffect(() => {
    fetchTasks();
  }, []);

  // Listen for external events to load snapshot and generate tasks
  useEffect(() => {
    function onSetSnapshot(e: Event) {
      const detail = (e as CustomEvent).detail as { snapshot?: ScrapeSnapshot }
      if (detail?.snapshot) setLatestSnapshot(detail.snapshot)
    }
    async function onGenerate(e: Event) {
      const detail = (e as CustomEvent).detail as { snapshot?: ScrapeSnapshot }
      const snapshot = detail?.snapshot || latestSnapshot
      if (!snapshot) return toast.warning("No snapshot provided for generation")
      try {
        const siteId = typeof window !== 'undefined' ? (localStorage.getItem('mudra:siteId') || '') : '';
        const res = await fetch("/api/tasks/generate", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ snapshot, siteId }),
        })
        const json = await res.json()
        if (!res.ok || !json?.success) throw new Error(json?.error?.message || "Failed to generate tasks")
        
        toast.success(`Generated ${json.data?.taskIds?.length || 0} new tasks`)
        // Refresh tasks from database
        await fetchTasks()
      } catch (err: any) {
        toast.error(err?.message || "Failed to generate tasks")
      }
    }
    function onRefreshTasks() {
      fetchTasks()
    }
    window.addEventListener("mudra:set-latest-snapshot" as any, onSetSnapshot as any)
    window.addEventListener("mudra:generate-tasks" as any, onGenerate as any)
    window.addEventListener("mudra:refresh-tasks" as any, onRefreshTasks as any)
    return () => {
      window.removeEventListener("mudra:set-latest-snapshot" as any, onSetSnapshot as any)
      window.removeEventListener("mudra:generate-tasks" as any, onGenerate as any)
      window.removeEventListener("mudra:refresh-tasks" as any, onRefreshTasks as any)
    }
  }, [latestSnapshot])

  const inProgressTasks = tasks.filter(task => task.status === "In Process")
  const completedTasks = tasks.filter(task => task.status === "Done")

  // AI Task Generator removed

  return (
    <div className="@container/main flex flex-1 flex-col gap-3 md:gap-4 bg-dark-grey">
      <div className="flex flex-col gap-5 md:gap-6 pb-6 md:pb-8">
        {/* Header Cards */}
        <div className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card grid grid-cols-1 gap-4 px-4 lg:px-6 mt-1 md:mt-2 *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs @xl/main:grid-cols-3">
          <MetricCard
            title="Total Tasks"
            value={tasks.length}
            status="Active"
            trend="up"
            icon="target"
          />
          <MetricCard
            title="In Progress"
            value={inProgressTasks.length}
            status="Processing"
            trend="neutral"
            icon="loader"
          />
          <MetricCard
            title="Completed"
            value={completedTasks.length}
            status="Done"
            trend="up"
            icon="check"
          />
        </div>

        {/* AI Task Generator removed */}

        {/* Main Table */}
        <div className="px-4 lg:px-6">
          <Card className="pt-2 bg-transparent backdrop-blur-sm rounded-lg border border-white/[0.06]">
            {tasks.length > 0 ? (
              <div className="overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow className="hover:bg-transparent">
                      <TableHead className="w-12"></TableHead>
                      <TableHead className="text-xs uppercase tracking-wide text-white/60">Task</TableHead>
                      <TableHead className="text-xs uppercase tracking-wide text-white/60">Section Type</TableHead>
                      <TableHead className="w-[150px] text-center text-xs uppercase tracking-wide text-white/60">Status</TableHead>
                      <TableHead className="text-right text-xs uppercase tracking-wide text-white/60">Priority</TableHead>
                      <TableHead className="w-12"></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {tasks.map((task, index) => (
                      <Dialog key={task.id}>
                        <DialogTrigger asChild>
                           <TableRow className="cursor-pointer align-middle transition-colors hover:bg-muted/40">
                            <TableCell>
                              <DragHandle id={task.id} />
                            </TableCell>
                            <TableCell className="font-medium">
                              {task.header}
                            </TableCell>
                            <TableCell>
                              <div className="w-32">
                                <Badge variant="outline" className="text-muted-foreground px-2 rounded">
                                  {task.type}
                                </Badge>
                              </div>
                            </TableCell>
                             <TableCell className="w-[150px] text-center">
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                  <Button variant="outline" size="sm" className="h-7 min-w-[110px] px-3 rounded">
                                    {task.status}
                                  </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="start" className="w-36">
                                  <DropdownMenuItem onClick={(e) => { e.preventDefault(); setTasks(prev => prev.map(t => t.id === task.id ? { ...t, status: 'In Process' } : t)) }}>In Process</DropdownMenuItem>
                                  <DropdownMenuItem onClick={(e) => { e.preventDefault(); setTasks(prev => prev.map(t => t.id === task.id ? { ...t, status: 'Done' } : t)) }}>Done</DropdownMenuItem>
                                </DropdownMenuContent>
                              </DropdownMenu>
                            </TableCell>
                             <TableCell className="text-right">
                               <PriorityTag level={task.priority as 'high' | 'medium' | 'low'} />
                             </TableCell>
                            <TableCell>
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                   <Button variant="ghost" className="text-muted-foreground/80 hover:text-white flex size-8" size="icon">
                                    <IconDotsVertical />
                                    <span className="sr-only">Open menu</span>
                                  </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end" className="w-32">
                                  <DropdownMenuItem>Edit</DropdownMenuItem>
                                  <DropdownMenuItem>View Details</DropdownMenuItem>
                                  <DropdownMenuItem>Duplicate</DropdownMenuItem>
                                  <DropdownMenuSeparator />
                                  <DropdownMenuItem variant="destructive">Delete</DropdownMenuItem>
                                </DropdownMenuContent>
                              </DropdownMenu>
                            </TableCell>
                          </TableRow>
                        </DialogTrigger>
                       <TaskDetailModal
                         task={task}
                         displayIndex={index + 1}
                         onComplete={(taskId) =>
                           setTasks((prev) => prev.map((t) => (t.id === taskId ? { ...t, status: 'Done' } : t)))
                         }
                         onVerify={task.templateKey ? async (taskId) => {
                           const t = tasks.find(x => x.id === taskId)
                           if (!t?.templateKey) return
                           if (!latestSnapshot) return toast.warning("No latest snapshot to verify against")
                           try {
                             const res = await fetch("/api/tasks/verify", {
                               method: "POST",
                               headers: { "content-type": "application/json" },
                               body: JSON.stringify({ latestSnapshot, task: { templateKey: t.templateKey } }),
                             })
                             const json = await res.json()
                             const passed = Boolean(json?.data?.passed)
                             if (passed) {
                               setTasks(prev => prev.map(x => x.id === taskId ? { ...x, status: 'Done' } : x))
                               toast.success("Task verified")
                             } else {
                               toast.info("Verification did not pass yet")
                             }
                           } catch (e: any) {
                             toast.error(e?.message || "Verification failed")
                           }
                         } : undefined}
                       />
                      </Dialog>
                    ))}
                  </TableBody>
                </Table>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-16 px-6">
                <div className="flex flex-col items-center max-w-md text-center w-full">
                  <div className="relative w-full max-w-md bg-transparent backdrop-blur-sm rounded-xl border border-white/[0.08] p-6 shadow-xl overflow-hidden group">
                    <div className="text-center mb-5">
                      <h3 className="text-xl font-semibold text-white tracking-tight mb-2">
                        No Tasks Generated Yet
                      </h3>
                      <p className="text-sm text-white/60 leading-relaxed">
                        Use the AI Task Generator above to analyze a website and get personalized GEO optimization tasks, 
                        or click the Magic Button to analyze a site and generate tasks automatically.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </Card>
        </div>
      </div>
    </div>
  )
} 