"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardAction,
  CardDescription,
  CardHeader,
  CardTitle,
  CardContent,
} from "@/components/ui/card"
import { MetricCard } from "@/components/dashboard/metric-card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"
import { 
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from "@/components/ui/dialog"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Progress } from "@/components/ui/progress"
import { 
  IconGripVertical,
  IconDotsVertical,
  IconTarget,
  IconExternalLink,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
} from "@tabler/icons-react"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { useState } from "react"
import { FloatingMudraButton } from "@/components/floating-mudra-button"

// AI Task Generator removed

// Define types
type TaskItem = {
  id: number
  header: string
  type: "GEO" | "SEO" | "Content"
  status: string
  target: string
  limit: string
  progress: number
  priority: string
  dueDate: string
  description: string
  actionItems: string[]
  detailedSteps: DetailedStep[]
  resources: Resource[]
  estimatedTime: string
  difficulty: string
  whyItMatters: string
  impact: string
}

type DetailedStep = {
  id: number
  title: string
  description: string
  completed: boolean
  estimatedTime: string
}

type Resource = {
  title: string
  url: string
  type: "documentation" | "tool" | "guide"
}

// AI Task transformation removed

// Removed static tasks - tasks only appear when generated by AI

function DragHandle({ id }: { id: number }) {
  return (
    <Button
      variant="ghost"
      size="icon"
      className="text-white/40 hover:text-white/80 size-7 hover:bg-transparent"
    >
      <IconGripVertical className="size-3" />
      <span className="sr-only">Drag to reorder</span>
    </Button>
  )
}

function PriorityTag({ level }: { level: 'high' | 'medium' | 'low' }) {
  const color = level === 'high' ? 'bg-red-500' : level === 'medium' ? 'bg-amber-500' : 'bg-green-500'
  const label = level === 'high' ? 'High importance' : level === 'medium' ? 'Medium priority' : 'Low priority'
  const bar = `w-1 h-3 rounded-[3px] ring-1 ring-white/10 ${color}`
  return (
    <div className="inline-flex items-center gap-1" aria-label={label} title={label}>
      <span aria-hidden className={bar}></span>
      <span aria-hidden className={bar}></span>
      <span aria-hidden className={bar}></span>
    </div>
  )
}

function TaskDetailModal({ task, onComplete }: { task: TaskItem; onComplete: (taskId: number) => void }) {
  const [stepStates, setStepStates] = useState<Record<number, boolean>>({})
  const [expandedStepId, setExpandedStepId] = useState<number | null>(null)

  const toggleStep = (stepId: number) => {
    setStepStates(prev => ({
      ...prev,
      [stepId]: !prev[stepId]
    }))
  }

  const completedSteps = Object.values(stepStates).filter(Boolean).length
  const totalSteps = task.detailedSteps.length
  const progressPercentage = totalSteps > 0 ? (completedSteps / totalSteps) * 100 : 0
  const allStepsDone = totalSteps > 0 && completedSteps === totalSteps

  return (
    <DialogContent className="max-w-6xl max-h-[86vh] p-6 md:p-8 bg-white/[0.02] backdrop-blur-sm border border-white/10 rounded-2xl flex flex-col">
      <DialogHeader className="pb-3">
        <div className="flex items-start">
          <div>
            <DialogTitle className="text-lg leading-snug font-semibold text-white">
              {task.header}
            </DialogTitle>
            <DialogDescription className="mt-1 text-[13px] md:text-sm text-white/70">
              {task.description}
            </DialogDescription>
          </div>
        </div>
      </DialogHeader>

      <div className="flex-1 overflow-y-auto pr-0 mt-2">
        <Tabs defaultValue="overview" className="px-1">
          <div className="flex items-center justify-between mb-4">
            <TabsList className="bg-white/[0.04] border border-white/10 rounded-xl p-1.5 gap-1">
              <TabsTrigger value="overview">Overview</TabsTrigger>
              <TabsTrigger value="steps">Steps</TabsTrigger>
              <TabsTrigger value="resources">Resources</TabsTrigger>
            </TabsList>
            <div className="flex items-center gap-2">
              <Badge variant="outline" className="h-7 rounded-full text-xs whitespace-nowrap">Priority: {task.priority}</Badge>
            </div>
          </div>

          <TabsContent value="overview">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 md:gap-4">
              <Card className="min-h-[120px] py-4 *:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Progress</CardDescription>
                  <CardTitle className="text-2xl font-bold text-foreground">{progressPercentage.toFixed(0)}%</CardTitle>
                </CardHeader>
              </Card>
              <Card className="min-h-[120px] py-4 *:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Difficulty</CardDescription>
                  <CardTitle className="text-lg font-semibold text-foreground">{task.difficulty}</CardTitle>
                </CardHeader>
              </Card>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 md:gap-4 mt-4">
              <Card className="py-4">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Why it matters</CardDescription>
                  <CardContent className="px-0 pt-2">
                    <p className="text-sm text-muted-foreground leading-relaxed">{task.whyItMatters}</p>
                  </CardContent>
                </CardHeader>
              </Card>
              <Card className="py-4">
                <CardHeader className="pb-2">
                  <CardDescription className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Impact</CardDescription>
                  <CardContent className="px-0 pt-2">
                    <p className="text-sm text-muted-foreground leading-relaxed">{task.impact}</p>
                  </CardContent>
                </CardHeader>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="steps">
            {task.detailedSteps.length > 0 && (
            <Card className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs mb-4">
                <CardHeader className="pb-4">
                  <CardTitle className="text-lg font-semibold">Step Progress</CardTitle>
                  <CardDescription className="text-muted-foreground/80">
                    {completedSteps} of {totalSteps} steps completed
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <Progress value={progressPercentage} className="h-3" />
                </CardContent>
              </Card>
            )}
            <Card className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
              <CardHeader className="pb-4">
                <CardTitle className="text-lg font-semibold">Checklist</CardTitle>
                <CardDescription className="text-muted-foreground/80">Follow these steps</CardDescription>
              </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {task.detailedSteps.map((step, index) => (
                  <div
                    key={step.id}
                    className={`group rounded-xl border border-white/10 p-4 bg-white/[0.03] hover:bg-white/[0.05] transition-all duration-200 cursor-pointer ${expandedStepId === step.id ? 'ring-1 ring-white/20' : ''} ${stepStates[step.id] ? 'border-emerald-500/30' : ''}`}
                    aria-expanded={expandedStepId === step.id}
                    onClick={() => setExpandedStepId(prev => (prev === step.id ? null : step.id))}
                  >
                    <div className="flex gap-3">
                      <div className={`mt-0.5 flex h-6 w-6 items-center justify-center rounded-full text-[11px] font-medium ${stepStates[step.id] ? 'bg-emerald-500/20 text-emerald-300' : 'bg-white/10 text-white/70'}`}>{index + 1}</div>
                      <div className="flex-shrink-0 mt-0.5" onClick={(e) => e.stopPropagation()}>
                        <Checkbox
                          checked={stepStates[step.id] || false}
                          onCheckedChange={() => toggleStep(step.id)}
                        />
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <h4 className="font-semibold text-white">{step.title}</h4>
                          <div className="ml-auto text-white/60">
                            {expandedStepId === step.id ? (
                              <IconChevronDown className="size-4" />
                            ) : (
                              <IconChevronRight className="size-4" />
                            )}
                          </div>
                        </div>
                        <p className="text-sm text-white/80 leading-relaxed">{step.description}</p>

                        {expandedStepId === step.id && (
                          <div className="mt-3 pt-3 border-t border-white/10 space-y-3">
                            <h5 className="text-sm font-semibold">Detailed instructions</h5>
                            <ol className="list-decimal ml-5 space-y-2 text-sm text-muted-foreground">
                              <li>Prepare: identify the exact files and locations impacted by “{step.title}”. Create a backup or a new branch before changes.</li>
                              <li>Implement: follow the step description precisely. If adding code or JSON-LD, validate with appropriate linters/validators.</li>
                              <li>Verify: test locally and in a staging environment. Use browser devtools and network/SEO tools to confirm results.</li>
                              <li>Document: capture a short note of what changed and why so teammates can follow the context later.</li>
                            </ol>
                            <p className="text-xs text-white/60">Tip: Click the checkbox on the left to mark this step as completed.</p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="resources">
            <Card className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs">
              <CardHeader className="pb-4">
                <CardTitle className="text-lg font-semibold">Helpful Resources</CardTitle>
                <CardDescription className="text-muted-foreground/80">Tools and guides</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {task.resources.map((resource, index) => (
                    <a key={index} href={resource.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 p-3 border border-white/10 rounded-xl bg-white/[0.03] hover:bg-white/[0.05] transition-colors">
                      <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center">
                        <IconExternalLink className="size-4 text-primary" />
                      </div>
                      <div className="flex-1">
                        <p className="font-semibold text-sm text-white">{resource.title}</p>
                        <p className="text-xs text-white/70 capitalize">{resource.type}</p>
                      </div>
                    </a>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          
        </Tabs>

        <div className="grid grid-cols-2 gap-5 pt-4">
          <DialogClose asChild>
            <Button
              disabled={!allStepsDone}
              onClick={() => onComplete(task.id)}
              className={`w-full h-11 rounded-xl gap-2 ${allStepsDone ? 'bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary/70' : 'bg-white/5 text-white/40 cursor-not-allowed'}`}
            >
              <IconCheck className="size-4" />
              Mark as Complete
            </Button>
          </DialogClose>
          <Button
            variant="outline"
            className="w-full h-11 rounded-xl"
            onClick={() => {
              // Close any open dialog by dispatching Escape
              document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
              // Open chat popup
              window.dispatchEvent(new Event('mudra:open-chat'))
            }}
          >
            Ask AI
          </Button>
        </div>
      </div>
    </DialogContent>
  )
}

export function TasksView() {
  const [tasks, setTasks] = useState<TaskItem[]>([
    {
      id: 1,
      header: "Implement Organization & WebSite Schema",
      type: "SEO",
      status: "In Process",
      target: "0",
      limit: "100",
      progress: 0,
      priority: "high",
      dueDate: "2025-01-01",
      description: "Add missing Organization and WebSite JSON-LD to improve AI visibility and entity understanding.",
      whyItMatters: "Structured data helps AI and search engines correctly understand your brand, improving the chance of accurate mentions and rich results.",
      impact: "Higher entity confidence across AI systems; potential uplift in brand mentions and richer snippets in model answers.",
      actionItems: [
        "Add Organization JSON-LD on homepage",
        "Add WebSite schema with SearchAction"
      ],
      detailedSteps: [
        {
          id: 1,
          title: "Add Organization JSON-LD",
          description: "Insert Organization schema in the <head> with name, url, logo, and contactPoint.",
          completed: false,
          estimatedTime: "1.5 hours"
        },
        {
          id: 2,
          title: "Add WebSite JSON-LD with SearchAction",
          description: "Provide site name, url, and a SearchAction template for on-site search URLs.",
          completed: false,
          estimatedTime: "1 hour"
        }
      ],
      resources: [
        { title: "Schema.org Organization", url: "https://schema.org/Organization", type: "documentation" },
        { title: "Schema.org WebSite", url: "https://schema.org/WebSite", type: "documentation" }
      ],
      estimatedTime: "3-4 hours",
      difficulty: "medium"
    },
    {
      id: 2,
      header: "Fix Critical Technical Issues Blocking AI Crawlers",
      type: "SEO",
      status: "In Process",
      target: "0",
      limit: "100",
      progress: 0,
      priority: "high",
      dueDate: "2025-01-10",
      description: "Address missing meta tags and slow load performance to ensure AI crawlers can properly index content.",
      whyItMatters: "Technical blockers degrade crawlability and can prevent AI systems from trusting or surfacing your content.",
      impact: "Faster, more reliable indexing; improved eligibility for AI citations due to better page health.",
      actionItems: [
        "Add title and meta description",
        "Optimize image sizes and compression",
        "Enable gzip/brotli and caching"
      ],
      detailedSteps: [
        {
          id: 1,
          title: "Add Optimized Title & Meta Description",
          description: "Ensure a 50–60 char title and a 150–160 char meta description exist on key pages.",
          completed: false,
          estimatedTime: "45 minutes"
        },
        {
          id: 2,
          title: "Improve Performance",
          description: "Convert large images to WebP/AVIF, lazy-load below‑the‑fold assets, and enable gzip/brotli.",
          completed: false,
          estimatedTime: "2 hours"
        }
      ],
      resources: [
        { title: "PageSpeed Insights", url: "https://pagespeed.web.dev/", type: "tool" },
        { title: "Meta Tags Guide", url: "https://developer.mozilla.org/docs/Web/HTML/Element/meta", type: "documentation" }
      ],
      estimatedTime: "2–3 hours",
      difficulty: "medium"
    },
    {
      id: 3,
      header: "Build Content Authority Signals for AI Trust",
      type: "Content",
      status: "In Process",
      target: "0",
      limit: "100",
      progress: 0,
      priority: "medium",
      dueDate: "2025-01-15",
      description: "Increase credible citations and expert signals to raise AI citation likelihood.",
      whyItMatters: "Authority signals guide AI systems to trust and reference your content over competitors.",
      impact: "Greater likelihood of brand inclusion in AI answers and improved perceived expertise.",
      actionItems: [
        "Add 5 authoritative statistics with sources",
        "Include expert quote/testimonial",
        "Create author bio with credentials"
      ],
      detailedSteps: [
        {
          id: 1,
          title: "Research and Add Statistics",
          description: "Add recent, cited data points to relevant sections with source links and dates.",
          completed: false,
          estimatedTime: "1.5 hours"
        },
        {
          id: 2,
          title: "Author Bio & Expert Quote",
          description: "Create an author block with credentials and add one expert quote or customer testimonial.",
          completed: false,
          estimatedTime: "1 hour"
        }
      ],
      resources: [
        { title: "Google E‑E‑A‑T", url: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content", type: "guide" },
        { title: "Statista", url: "https://www.statista.com/", type: "tool" }
      ],
      estimatedTime: "2.5–3 hours",
      difficulty: "easy"
    }
  ])

  const inProgressTasks = tasks.filter(task => task.status === "In Process")
  const completedTasks = tasks.filter(task => task.status === "Done")

  // AI Task Generator removed

  return (
    <div className="@container/main flex flex-1 flex-col gap-3 md:gap-4 bg-dark-grey">
      <div className="flex flex-col gap-5 md:gap-6 pb-6 md:pb-8">
        {/* Header Cards */}
        <div className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card grid grid-cols-1 gap-4 px-4 lg:px-6 mt-1 md:mt-2 *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs @xl/main:grid-cols-3">
          <MetricCard
            title="Total Tasks"
            value={tasks.length}
            status="Active"
            trend="up"
            icon="target"
          />
          <MetricCard
            title="In Progress"
            value={inProgressTasks.length}
            status="Processing"
            trend="neutral"
            icon="loader"
          />
          <MetricCard
            title="Completed"
            value={completedTasks.length}
            status="Done"
            trend="up"
            icon="check"
          />
        </div>

        {/* AI Task Generator removed */}

        {/* Main Table */}
        <div className="px-4 lg:px-6">
          <Card className="pt-2 bg-white/[0.02] backdrop-blur-sm rounded-2xl border border-white/[0.06]">
            {tasks.length > 0 ? (
              <div className="overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow className="hover:bg-transparent">
                      <TableHead className="w-12"></TableHead>
                      <TableHead className="text-xs uppercase tracking-wide text-white/60">Task</TableHead>
                      <TableHead className="text-xs uppercase tracking-wide text-white/60">Section Type</TableHead>
                      <TableHead className="w-[150px] text-center text-xs uppercase tracking-wide text-white/60">Status</TableHead>
                      <TableHead className="text-right text-xs uppercase tracking-wide text-white/60">Priority</TableHead>
                      <TableHead className="w-12"></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {tasks.map((task) => (
                      <Dialog key={task.id}>
                        <DialogTrigger asChild>
                           <TableRow className="cursor-pointer align-middle transition-colors hover:bg-muted/40">
                            <TableCell>
                              <DragHandle id={task.id} />
                            </TableCell>
                            <TableCell className="font-medium">
                              {task.header}
                            </TableCell>
                            <TableCell>
                              <div className="w-32">
                                <Badge variant="outline" className="text-muted-foreground px-2 rounded-full">
                                  {task.type}
                                </Badge>
                              </div>
                            </TableCell>
                             <TableCell className="w-[150px] text-center">
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                  <Button variant="outline" size="sm" className="h-7 min-w-[110px] px-3 rounded-full">
                                    {task.status}
                                  </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="start" className="w-36">
                                  <DropdownMenuItem onClick={(e) => { e.preventDefault(); setTasks(prev => prev.map(t => t.id === task.id ? { ...t, status: 'In Process' } : t)) }}>In Process</DropdownMenuItem>
                                  <DropdownMenuItem onClick={(e) => { e.preventDefault(); setTasks(prev => prev.map(t => t.id === task.id ? { ...t, status: 'Done' } : t)) }}>Done</DropdownMenuItem>
                                </DropdownMenuContent>
                              </DropdownMenu>
                            </TableCell>
                             <TableCell className="text-right">
                               <PriorityTag level={task.priority as 'high' | 'medium' | 'low'} />
                             </TableCell>
                            <TableCell>
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                   <Button variant="ghost" className="text-muted-foreground/80 hover:text-white flex size-8" size="icon">
                                    <IconDotsVertical />
                                    <span className="sr-only">Open menu</span>
                                  </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end" className="w-32">
                                  <DropdownMenuItem>Edit</DropdownMenuItem>
                                  <DropdownMenuItem>View Details</DropdownMenuItem>
                                  <DropdownMenuItem>Duplicate</DropdownMenuItem>
                                  <DropdownMenuSeparator />
                                  <DropdownMenuItem variant="destructive">Delete</DropdownMenuItem>
                                </DropdownMenuContent>
                              </DropdownMenu>
                            </TableCell>
                          </TableRow>
                        </DialogTrigger>
                       <TaskDetailModal
                         task={task}
                         onComplete={(taskId) =>
                           setTasks((prev) => prev.map((t) => (t.id === taskId ? { ...t, status: 'Done' } : t)))
                         }
                       />
                      </Dialog>
                    ))}
                  </TableBody>
                </Table>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <IconTarget className="h-12 w-12 text-muted-foreground mb-4" />
                <h3 className="text-lg font-semibold mb-2">No Tasks Generated Yet</h3>
                <p className="text-muted-foreground text-sm max-w-md">
                  Use the AI Task Generator above to analyze a website and get personalized GEO optimization tasks, 
                  or click the Magic Button to analyze a site and generate tasks automatically.
                </p>
              </div>
            )}
          </Card>
        </div>
      </div>
      
      {/* Context-aware AI Chat */}
      <FloatingMudraButton 
        taskContext={tasks.map(task => ({
          id: task.id,
          header: task.header,
          type: task.type,
          status: task.status,
          description: task.description,
          detailedSteps: task.detailedSteps,
          resources: task.resources,
          estimatedTime: task.estimatedTime,
          difficulty: task.difficulty
        }))}
      />
    </div>
  )
} 