"use client"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardAction,
  CardDescription,
  CardHeader,
  CardTitle,
  CardContent,
} from "@/components/ui/card"
import { MetricCard } from "@/components/dashboard/metric-card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Progress } from "@/components/ui/progress"
import { 
  IconCircleCheckFilled,
  IconLoader,
  IconGripVertical,
  IconDotsVertical,
  IconTrendingUp,
  IconPlus,
  IconTarget,
  IconClock,
  IconExternalLink,
  IconCheck,
} from "@tabler/icons-react"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { useState, useEffect } from "react"
import { useSearchParams } from "next/navigation"

import type { AIGeneratedTask } from "@/lib/services/ai-task-generation.service"

// Define types
type TaskItem = {
  id: number
  header: string
  type: string
  status: string
  target: string
  limit: string
  progress: number
  priority: string
  dueDate: string
  description: string
  actionItems: string[]
  detailedSteps: DetailedStep[]
  resources: Resource[]
  estimatedTime: string
  difficulty: string
}

type DetailedStep = {
  id: number
  title: string
  description: string
  completed: boolean
  estimatedTime: string
}

type Resource = {
  title: string
  url: string
  type: "documentation" | "tool" | "guide"
}

// Transform AI tasks to TaskItem format
const transformAITasksToTaskItems = (aiTasks: AIGeneratedTask[]): TaskItem[] => {
  return aiTasks.map((task, index) => ({
    id: index + 1,
    header: task.title,
    type: task.category,
    status: "In Process",
    target: "0",
    limit: "100",
    progress: 0,
    priority: task.priority,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 7 days from now
    description: task.description,
    actionItems: task.steps.map(step => step.title),
    detailedSteps: task.steps.map((step, i) => ({
      id: i + 1,
      title: step.title,
      description: step.description,
      completed: false,
      estimatedTime: step.estimatedTime
    })),
    resources: task.resources,
    estimatedTime: task.estimatedTime,
    difficulty: task.difficulty
  }))
}

// Removed static tasks - tasks only appear when generated by AI

function DragHandle({ id }: { id: number }) {
  return (
    <Button
      variant="ghost"
      size="icon"
      className="text-muted-foreground size-7 hover:bg-transparent"
    >
      <IconGripVertical className="text-muted-foreground size-3" />
      <span className="sr-only">Drag to reorder</span>
    </Button>
  )
}

function TaskDetailModal({ task }: { task: TaskItem }) {
  const [stepStates, setStepStates] = useState<Record<number, boolean>>({})

  const toggleStep = (stepId: number) => {
    setStepStates(prev => ({
      ...prev,
      [stepId]: !prev[stepId]
    }))
  }

  const completedSteps = Object.values(stepStates).filter(Boolean).length
  const totalSteps = task.detailedSteps.length
  const progressPercentage = totalSteps > 0 ? (completedSteps / totalSteps) * 100 : 0

  return (
    <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
      <DialogHeader>
        <DialogTitle className="flex items-center gap-2">
          <IconTarget className="size-5" />
          {task.header}
        </DialogTitle>
        <DialogDescription>
          {task.description}
        </DialogDescription>
      </DialogHeader>

      <div className="space-y-6">
        {/* Task Overview */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card>
            <CardHeader className="pb-3">
              <CardDescription>Progress</CardDescription>
              <CardTitle className="text-2xl">{task.progress}%</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-3">
              <CardDescription>Estimated Time</CardDescription>
              <CardTitle className="text-lg">{task.estimatedTime}</CardTitle>
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="pb-3">
              <CardDescription>Difficulty</CardDescription>
              <CardTitle className="text-lg">{task.difficulty}</CardTitle>
            </CardHeader>
          </Card>
        </div>

        {/* Steps Progress */}
        {task.detailedSteps.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Step Progress</CardTitle>
              <CardDescription>
                {completedSteps} of {totalSteps} steps completed
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Progress value={progressPercentage} className="h-2" />
            </CardContent>
          </Card>
        )}

        {/* Detailed Steps */}
        {task.detailedSteps.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>What You Need to Do</CardTitle>
              <CardDescription>
                Follow these steps to complete the task
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {task.detailedSteps.map((step, index) => (
                  <div key={step.id} className="flex gap-4 p-4 border rounded-lg">
                    <div className="flex-shrink-0 mt-1">
                      <Checkbox
                        checked={stepStates[step.id] || false}
                        onCheckedChange={() => toggleStep(step.id)}
                      />
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <h4 className="font-medium">
                          Step {index + 1}: {step.title}
                        </h4>
                        <Badge variant="outline" className="text-xs">
                          <IconClock className="size-3 mr-1" />
                          {step.estimatedTime}
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {step.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Resources */}
        {task.resources.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Helpful Resources</CardTitle>
              <CardDescription>
                Tools and guides to help you complete this task
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {task.resources.map((resource, index) => (
                  <div key={index} className="flex items-center gap-3 p-3 border rounded-lg hover:bg-muted/50">
                    <IconExternalLink className="size-4 text-muted-foreground" />
                    <div className="flex-1">
                      <p className="font-medium text-sm">{resource.title}</p>
                      <p className="text-xs text-muted-foreground capitalize">{resource.type}</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Action Buttons */}
        <div className="flex gap-2 pt-4">
          <Button className="flex-1">
            <IconCheck className="size-4 mr-2" />
            Mark as Complete
          </Button>
          <Button variant="outline">
            <IconClock className="size-4 mr-2" />
            Start Timer
          </Button>
        </div>
      </div>
    </DialogContent>
  )
}

export function TasksView() {
  const [tasks, setTasks] = useState<TaskItem[]>([])
  const [loading, setLoading] = useState(false)
  const [url, setUrl] = useState('')
  const [companyContext, setCompanyContext] = useState('')
  const [analysisData, setAnalysisData] = useState<any>(null)
  const [autoGenerated, setAutoGenerated] = useState(false)

  const searchParams = useSearchParams()
  const cached = searchParams?.get('cached') === 'true'

  const inProgressTasks = tasks.filter(task => task.status === "In Process")
  const completedTasks = tasks.filter(task => task.status === "Done")

  const generateAITasks = async (cachedResults?: any) => {
    // If using cached results, skip URL validation
    if (!cachedResults && !url.trim()) {
      alert('Please enter a website URL')
      return
    }

    setLoading(true)
    try {
      if (cachedResults) {
        console.log('🔍 Generating AI tasks from cached results')
      } else {
        console.log('🔍 Generating AI tasks for:', url)
      }
      
      const requestBody = cachedResults
        ? {
            cachedGeoResults: cachedResults,
            companyContext: companyContext.trim() || undefined
          }
        : {
            url: url.trim(),
            companyContext: companyContext.trim() || undefined
          }
      
      const response = await fetch('/api/ai-tasks/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody)
      })

      const result = await response.json()

      if (!result.success) {
        throw new Error(result.error || 'Failed to generate AI tasks')
      }

      console.log('✅ AI tasks generated successfully:', result.data)
      
      // Transform AI tasks to TaskItem format
      const aiTasks = transformAITasksToTaskItems(result.data.tasks)
      setTasks(aiTasks)
      setAnalysisData(result.data.geoResults)
      
    } catch (error) {
      console.error('❌ Failed to generate AI tasks:', error)
      alert(`Failed to generate AI tasks: ${error instanceof Error ? error.message : 'Unknown error'}`)
    } finally {
      setLoading(false)
    }
  }

  const clearTasks = () => {
    setTasks([])
    setAnalysisData(null)
    setUrl('')
    setCompanyContext('')
    setAutoGenerated(false)
  }

  // Auto-generate tasks from cached results
  useEffect(() => {
    if (cached && !autoGenerated && !loading && typeof window !== 'undefined') {
      const cachedResults = sessionStorage.getItem('cachedGeoResults')
      if (cachedResults) {
        try {
          const geoResults = JSON.parse(cachedResults)
          setAutoGenerated(true)
          setAnalysisData(geoResults)
          setUrl(geoResults.url || '')
          generateAITasks(geoResults)
          
          // Clear cached results after use
          sessionStorage.removeItem('cachedGeoResults')
        } catch (error) {
          console.error('Failed to parse cached results:', error)
        }
      }
    }
  }, [cached, autoGenerated, loading])

  return (
    <div className="@container/main flex flex-1 flex-col gap-2 bg-black">
      <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
        {/* Header Cards */}
        <div className="*:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card dark:*:data-[slot=card]:bg-card grid grid-cols-1 gap-4 px-4 *:data-[slot=card]:bg-gradient-to-t *:data-[slot=card]:shadow-xs lg:px-6 @xl/main:grid-cols-3">
          <MetricCard
            title="Total Tasks"
            value={tasks.length}
            status="Active"
            trend="up"
            icon="target"
          />
          <MetricCard
            title="In Progress"
            value={inProgressTasks.length}
            status="Processing"
            trend="neutral"
            icon="loader"
          />
          <MetricCard
            title="Completed"
            value={completedTasks.length}
            status="Done"
            trend="up"
            icon="check"
          />
        </div>

        {/* AI Task Generation Form */}
        <div className="px-4 lg:px-6">
          <Card>
            <CardHeader>
              <CardTitle>🤖 AI Task Generator</CardTitle>
              <CardDescription>
                {cached && autoGenerated 
                  ? "AI tasks generated from your recent analysis" 
                  : "Analyze any website and get AI-generated GEO optimization tasks"
                }
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="website-url">Website URL</Label>
                    <Input
                      id="website-url"
                      placeholder="https://example.com"
                      value={url}
                      onChange={(e) => setUrl(e.target.value)}
                      disabled={loading}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="company-context">Company Context (Optional)</Label>
                    <Input
                      id="company-context"
                      placeholder="e.g., SaaS startup, fintech company..."
                      value={companyContext}
                      onChange={(e) => setCompanyContext(e.target.value)}
                      disabled={loading}
                    />
                  </div>
                </div>
                
                <div className="flex gap-2">
                  <Button 
                    onClick={generateAITasks} 
                    disabled={loading || !url.trim()}
                    className="flex-1 md:flex-none"
                  >
                    {loading ? (
                      <>
                        <IconLoader className="size-4 mr-2 animate-spin" />
                        Analyzing Website...
                      </>
                    ) : (
                      <>
                        <IconTrendingUp className="size-4 mr-2" />
                        Generate AI Tasks
                      </>
                    )}
                  </Button>
                  
                  {analysisData && (
                    <Button variant="outline" onClick={clearTasks}>
                      Clear Tasks
                    </Button>
                  )}
                </div>
                
                {analysisData && (
                  <div className="mt-4 p-4 bg-muted/50 rounded-lg">
                    <h4 className="font-medium mb-2">🎯 Analysis Results for {analysisData.url}</h4>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-sm">
                      <div>Overall: <Badge variant="outline">{analysisData.geoScore.overall}/100</Badge></div>
                      <div>Structured Data: <Badge variant="outline">{analysisData.geoScore.structuredData}/100</Badge></div>
                      <div>Technical: <Badge variant="outline">{analysisData.geoScore.technicalAccessibility}/100</Badge></div>
                      <div>Content: <Badge variant="outline">{analysisData.geoScore.contentAuthority}/100</Badge></div>
                    </div>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Main Table */}
        <div className="px-4 lg:px-6">
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>
                    {tasks.length > 0 ? '🤖 AI-Generated Tasks' : '📋 No Tasks Yet'} 
                    {cached && autoGenerated && <span className="text-green-500 ml-2">✨ From Analysis</span>}
                  </CardTitle>
                  <CardDescription>
                    {tasks.length > 0 && analysisData 
                      ? `AI-generated GEO optimization tasks for ${analysisData.url}`
                      : 'Generate AI tasks by analyzing a website above'
                    }
                  </CardDescription>
                </div>
                <Button size="sm">
                  <IconPlus className="size-4" />
                  Add Task
                </Button>
              </div>
            </CardHeader>
            {tasks.length > 0 ? (
              <div className="overflow-hidden">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="w-12"></TableHead>
                      <TableHead className="w-12">
                        <div className="flex items-center justify-center">
                          <Checkbox aria-label="Select all" />
                        </div>
                      </TableHead>
                      <TableHead>Header</TableHead>
                      <TableHead>Section Type</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead className="text-right">Target</TableHead>
                      <TableHead className="text-right">Limit</TableHead>
                      <TableHead className="w-12"></TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {tasks.map((task) => (
                      <Dialog key={task.id}>
                        <DialogTrigger asChild>
                          <TableRow className="cursor-pointer hover:bg-muted/50">
                            <TableCell>
                              <DragHandle id={task.id} />
                            </TableCell>
                            <TableCell>
                              <div className="flex items-center justify-center">
                                <Checkbox aria-label="Select row" />
                              </div>
                            </TableCell>
                            <TableCell className="font-medium">
                              {task.header}
                            </TableCell>
                            <TableCell>
                              <div className="w-32">
                                <Badge variant="outline" className="text-muted-foreground px-1.5">
                                  {task.type}
                                </Badge>
                              </div>
                            </TableCell>
                            <TableCell>
                              <Badge variant="outline" className="text-muted-foreground px-1.5">
                                {task.status === "Done" ? (
                                  <IconCircleCheckFilled className="fill-green-500 dark:fill-green-400" />
                                ) : (
                                  <IconLoader />
                                )}
                                {task.status}
                              </Badge>
                            </TableCell>
                            <TableCell className="text-right">
                              <Label htmlFor={`${task.id}-target`} className="sr-only">
                                Target
                              </Label>
                              <Input
                                className="hover:bg-input/30 focus-visible:bg-background dark:hover:bg-input/30 dark:focus-visible:bg-input/30 h-8 w-16 border-transparent bg-transparent text-right shadow-none focus-visible:border dark:bg-transparent"
                                defaultValue={task.target}
                                id={`${task.id}-target`}
                              />
                            </TableCell>
                            <TableCell className="text-right">
                              <Label htmlFor={`${task.id}-limit`} className="sr-only">
                                Limit
                              </Label>
                              <Input
                                className="hover:bg-input/30 focus-visible:bg-background dark:hover:bg-input/30 dark:focus-visible:bg-input/30 h-8 w-16 border-transparent bg-transparent text-right shadow-none focus-visible:border dark:bg-transparent"
                                defaultValue={task.limit}
                                id={`${task.id}-limit`}
                              />
                            </TableCell>
                            <TableCell>
                              <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                  <Button
                                    variant="ghost"
                                    className="data-[state=open]:bg-muted text-muted-foreground flex size-8"
                                    size="icon"
                                  >
                                    <IconDotsVertical />
                                    <span className="sr-only">Open menu</span>
                                  </Button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end" className="w-32">
                                  <DropdownMenuItem>Edit</DropdownMenuItem>
                                  <DropdownMenuItem>View Details</DropdownMenuItem>
                                  <DropdownMenuItem>Duplicate</DropdownMenuItem>
                                  <DropdownMenuSeparator />
                                  <DropdownMenuItem variant="destructive">Delete</DropdownMenuItem>
                                </DropdownMenuContent>
                              </DropdownMenu>
                            </TableCell>
                          </TableRow>
                        </DialogTrigger>
                        <TaskDetailModal task={task} />
                      </Dialog>
                    ))}
                  </TableBody>
                </Table>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <IconTarget className="h-12 w-12 text-muted-foreground mb-4" />
                <h3 className="text-lg font-semibold mb-2">No Tasks Generated Yet</h3>
                <p className="text-muted-foreground text-sm max-w-md">
                  Use the AI Task Generator above to analyze a website and get personalized GEO optimization tasks, 
                  or click the Magic Button to analyze a site and generate tasks automatically.
                </p>
              </div>
            )}
          </Card>
        </div>
      </div>
    </div>
  )
} 