import { prisma } from '@/lib/prisma'
import crypto from 'crypto'
import jwt from 'jsonwebtoken'

// Encryption helpers
const ENCRYPTION_KEY = process.env.GITHUB_TOKEN_ENCRYPTION_KEY;
const ALGORITHM = 'aes-256-gcm';

function decrypt(encryptedText: string): string {
  if (!ENCRYPTION_KEY) {
    throw new Error('GITHUB_TOKEN_ENCRYPTION_KEY environment variable is required');
  }
  const [ivHex, authTagHex, encrypted] = encryptedText.split(':');
  const iv = Buffer.from(ivHex, 'hex');
  const authTag = Buffer.from(authTagHex, 'hex');
  const decipher = crypto.createDecipheriv(ALGORITHM, Buffer.from(ENCRYPTION_KEY, 'hex'), iv);
  decipher.setAuthTag(authTag);
  let decrypted = decipher.update(encrypted, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}

/**
 * Refresh GitHub App installation token
 */
async function refreshInstallationToken(installationId: number): Promise<string> {
  const appId = process.env.GITHUB_APP_ID;
  const privateKey = process.env.GITHUB_PRIVATE_KEY;
  
  if (!appId || !privateKey) {
    throw new Error('GitHub App credentials not configured');
  }
  
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    iat: now - 60,
    exp: now + 600,
    iss: appId,
  };
  
  const formattedKey = privateKey.replace(/\\n/g, '\n').trim();
  const appJwt = jwt.sign(payload, formattedKey, { algorithm: 'RS256' });
  
  const response = await fetch(
    `https://api.github.com/app/installations/${installationId}/access_tokens`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${appJwt}`,
        Accept: 'application/vnd.github+json',
      },
    }
  );
  
  if (!response.ok) {
    throw new Error('Failed to refresh installation token');
  }
  
  const data = await response.json();
  return data.token;
}

/**
 * Get a valid GitHub token for API calls
 */
async function getValidGitHubToken(integration: any): Promise<string> {
  if (integration.integrationType === 'installation' && integration.installationId) {
    const tokenExpiresAt = integration.tokenExpiresAt;
    const now = new Date();
    
    if (tokenExpiresAt && new Date(tokenExpiresAt).getTime() - now.getTime() < 5 * 60 * 1000) {
      return await refreshInstallationToken(integration.installationId);
    }
    
    try {
      return decrypt(integration.accessToken);
    } catch {
      return await refreshInstallationToken(integration.installationId);
    }
  }
  
  return decrypt(integration.accessToken);
}

interface CreateOptimizationPRInput {
  brandProfileId: number
  pageUrl: string
  improvements: Array<{
    type: string
    description: string
    code: string
    impact: string
    filePath?: string
  }>
  title: string
  description: string
}

interface PRResult {
  prUrl: string
  prNumber: number
}

/**
 * Create a GitHub PR with GEO optimization improvements
 */
export async function createOptimizationPR(input: CreateOptimizationPRInput): Promise<PRResult> {
  const { brandProfileId, pageUrl, improvements, title, description } = input

  // Get brand profile to access GitHub integration
  const brandProfile = await prisma.brandProfile.findUnique({
    where: { id: brandProfileId },
    include: {
      user: {
        include: {
          githubIntegration: true,
        },
      },
    },
  })

  if (!brandProfile || !brandProfile.user?.githubIntegration) {
    throw new Error('GitHub integration not found. Please connect your GitHub account in Settings → Integrations.')
  }

  const githubIntegration = brandProfile.user.githubIntegration

  // Get valid (decrypted and refreshed if needed) access token
  const accessToken = await getValidGitHubToken(githubIntegration)

  // Get repository information from agent schedule config
  const agentSchedule = await prisma.agentSchedule.findFirst({
    where: {
      brandProfileId,
      agentType: 'content_optimizer',
      isEnabled: true,
    },
  })

  if (!agentSchedule || !agentSchedule.config) {
    throw new Error('Agent not configured with repository. Please configure the Content Optimizer agent with your repository details.')
  }

  const config = agentSchedule.config as any
  const repoName = config.githubRepo
  const branch = config.githubBranch || 'main'

  if (!repoName) {
    throw new Error('GitHub repository not configured for Content Optimizer agent')
  }

  // Parse owner/repo
  const [owner, repo] = repoName.split('/')

  if (!owner || !repo) {
    throw new Error(`Invalid repository format: ${repoName}. Expected format: owner/repo`)
  }

  // Create a new branch name
  const branchName = `geo-optimization-${Date.now()}`

  // Prepare PR body with all improvements
  const prBody = `${description}

## Improvements

${improvements.map((imp, idx) => `
### ${idx + 1}. ${imp.description}
**Impact:** ${imp.impact.toUpperCase()}
**File:** \`${imp.filePath || 'index.html'}\`

\`\`\`html
${imp.code}
\`\`\`
`).join('\n')}

---
*Generated by Mudra Content Optimizer Agent*
`

  try {
    // Create PR using GitHub API
    const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github.v3+json',
      },
      body: JSON.stringify({
        title,
        body: prBody,
        head: branchName,
        base: branch,
      }),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(`GitHub API error: ${error.message || response.statusText}`)
    }

    const pr = await response.json()

    return {
      prUrl: pr.html_url,
      prNumber: pr.number,
    }
  } catch (error) {
    if (error instanceof Error) {
      throw error
    }
    throw new Error(`Failed to create PR: ${String(error)}`)
  }
}

/**
 * Get GitHub integration status for a user
 */
export async function getGitHubIntegrationStatus(userId: string) {
  const integration = await prisma.gitHubIntegration.findUnique({
    where: { userId },
  })

  return {
    isConnected: !!integration,
    username: integration?.githubUsername,
    avatarUrl: integration?.avatarUrl,
  }
}

/**
 * Save GitHub integration for a user
 */
export async function saveGitHubIntegration(data: {
  userId: string
  accessToken: string
  refreshToken?: string
  githubUserId: string
  githubUsername: string
  avatarUrl?: string
  scope?: string
}) {
  return prisma.gitHubIntegration.upsert({
    where: { userId: data.userId },
    create: {
      userId: data.userId,
      accessToken: data.accessToken, // TODO: Add encryption
      refreshToken: data.refreshToken,
      githubUserId: data.githubUserId,
      githubUsername: data.githubUsername,
      avatarUrl: data.avatarUrl,
      scope: data.scope,
      repositories: [],
    },
    update: {
      accessToken: data.accessToken,
      refreshToken: data.refreshToken,
      githubUsername: data.githubUsername,
      avatarUrl: data.avatarUrl,
      scope: data.scope,
      updatedAt: new Date(),
    },
  })
}
