import { prisma } from '@/lib/prisma'

interface CreateOptimizationPRInput {
  brandProfileId: number
  pageUrl: string
  improvements: Array<{
    type: string
    description: string
    code: string
    impact: string
    filePath?: string
  }>
  title: string
  description: string
}

interface PRResult {
  prUrl: string
  prNumber: number
}

/**
 * Create a GitHub PR with GEO optimization improvements
 */
export async function createOptimizationPR(input: CreateOptimizationPRInput): Promise<PRResult> {
  const { brandProfileId, pageUrl, improvements, title, description } = input

  // Get brand profile to access GitHub integration
  const brandProfile = await prisma.brandProfile.findUnique({
    where: { id: brandProfileId },
    include: {
      user: {
        include: {
          githubIntegration: true,
        },
      },
    },
  })

  if (!brandProfile || !brandProfile.user?.githubIntegration) {
    throw new Error('GitHub integration not found. Please connect your GitHub account in Settings → Integrations.')
  }

  const githubIntegration = brandProfile.user.githubIntegration

  // Decrypt access token
  const accessToken = githubIntegration.accessToken // Already encrypted in DB

  // Get repository information from agent schedule config
  const agentSchedule = await prisma.agentSchedule.findFirst({
    where: {
      brandProfileId,
      agentType: 'content_optimizer',
      isEnabled: true,
    },
  })

  if (!agentSchedule || !agentSchedule.config) {
    throw new Error('Agent not configured with repository. Please configure the Content Optimizer agent with your repository details.')
  }

  const config = agentSchedule.config as any
  const repoName = config.githubRepo
  const branch = config.githubBranch || 'main'

  if (!repoName) {
    throw new Error('GitHub repository not configured for Content Optimizer agent')
  }

  // Parse owner/repo
  const [owner, repo] = repoName.split('/')

  if (!owner || !repo) {
    throw new Error(`Invalid repository format: ${repoName}. Expected format: owner/repo`)
  }

  // Create a new branch name
  const branchName = `geo-optimization-${Date.now()}`

  // Prepare PR body with all improvements
  const prBody = `${description}

## Improvements

${improvements.map((imp, idx) => `
### ${idx + 1}. ${imp.description}
**Impact:** ${imp.impact.toUpperCase()}
**File:** \`${imp.filePath || 'index.html'}\`

\`\`\`html
${imp.code}
\`\`\`
`).join('\n')}

---
*Generated by Mudra Content Optimizer Agent*
`

  try {
    // Create PR using GitHub API
    const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github.v3+json',
      },
      body: JSON.stringify({
        title,
        body: prBody,
        head: branchName,
        base: branch,
      }),
    })

    if (!response.ok) {
      const error = await response.json()
      throw new Error(`GitHub API error: ${error.message || response.statusText}`)
    }

    const pr = await response.json()

    return {
      prUrl: pr.html_url,
      prNumber: pr.number,
    }
  } catch (error) {
    if (error instanceof Error) {
      throw error
    }
    throw new Error(`Failed to create PR: ${String(error)}`)
  }
}

/**
 * Get GitHub integration status for a user
 */
export async function getGitHubIntegrationStatus(userId: string) {
  const integration = await prisma.gitHubIntegration.findUnique({
    where: { userId },
  })

  return {
    isConnected: !!integration,
    username: integration?.githubUsername,
    avatarUrl: integration?.avatarUrl,
  }
}

/**
 * Save GitHub integration for a user
 */
export async function saveGitHubIntegration(data: {
  userId: string
  accessToken: string
  refreshToken?: string
  githubUserId: string
  githubUsername: string
  avatarUrl?: string
  scope?: string
}) {
  return prisma.gitHubIntegration.upsert({
    where: { userId: data.userId },
    create: {
      userId: data.userId,
      accessToken: data.accessToken, // TODO: Add encryption
      refreshToken: data.refreshToken,
      githubUserId: data.githubUserId,
      githubUsername: data.githubUsername,
      avatarUrl: data.avatarUrl,
      scope: data.scope,
      repositories: JSON.stringify([]),
    },
    update: {
      accessToken: data.accessToken,
      refreshToken: data.refreshToken,
      githubUsername: data.githubUsername,
      avatarUrl: data.avatarUrl,
      scope: data.scope,
      updatedAt: new Date(),
    },
  })
}
